# Generated by Django 3.2.8 on 2021-10-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.CharField(max_length=100)),
                ('summary', models.TextField(blank=True, max_length=300, null=True)),
                ('url', models.CharField(max_length=40, null=True)),
                ('duree', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=40)),
            ],
        ),
    ]
